### PR TITLE
Allow management toggle for listed tabs

### PR DESCRIPTION
**Pull request by robbiebowman**
# Change
- Allows adding and removing of tabs that are matched by regex rules to create specific exemptions.
    - Example use case: I am in manual mode and have a rule to mute any tab on youtube. I also however have a 10 hour lofi beats video which I want to play in background, despite also being on youtube.
    - I select manual mode, add my youtube regex, then navigate to my lofi beats tab and click the extension icon.
    - Now navigating away from the tab will not mute it.

https://github.com/igorlogius/mute-unfocused-tabs/assets/13639947/3f879245-7d9f-4782-9da4-226b3879c84c

## Minor changes
- Simplified some logic & code repetition
- Added a boilerplate git ignore
- Added an example regex rule in the readme

### CODE REVIEW

**Comment by igorlogius** [comment]
Hi. Thanks for the PR. I took a look at it. 

You are right in that the handling of the regex list was a bit inconsistent and bloated, so i tried to address this with `56cdcc5` and took inspriration from your PR.  It should now behave in a consistent manner.

Defaul: define exclusions / match are initally unmanaged tabs
Manual: define inclusions / matches are initally managed  tabs

States can be manually toggled/overwritten, via the toolbar icon, for the existence of a tabs lifetime. 

Besides, that i normally try and not commit metadata like .gitignore,package.json or other stuff into the repository.  Just what is needed to build the addon and some description. 

Sorry for not merging, but i thought this would be a little simpler. 

But if you find any other/addional issues, let me know and we can try and work them out.

**Comment by robbiebowman** [comment]
> Hi. Thanks for the PR. I took a look at it.
> 
> You are right in that the handling of the regex list was a bit inconsistent and bloated, so i tried to address this with `56cdcc5` and took inspriration from your PR. It should now behave in a consistent manner.
> 
> Defaul: define exclusions / match are initally unmanaged tabs Manual: define inclusions / matches are initally managed tabs
> 
> States can be manually toggled/overwritten, via the toolbar icon, for the existence of a tabs lifetime.
> 
> Besides, that i normally try and not commit metadata like .gitignore,package.json or other stuff into the repository. Just what is needed to build the addon and some description.
> 
> Sorry for not merging, but i thought this would be a little simpler.
> 
> But if you find any other/addional issues, let me know and we can try and work them out.

Meh. Kinda disappointing to have made 2 contributions to the repo and not get either PR's merged.

**Comment by igorlogius** [comment]
> Meh. Kinda disappointing to have made 2 contributions to the repo and not get either PR's merged.

Sorry, Sorry. i didn't want to upset you or downplay your efforts/help. 

I just dont have much experience with handeling PRs and doing reviews and i thought it might be to much back and forth involed .... But i guess i should have at least given it a short instead of acting on a whim  

Sorry again, i'll try to handle things better in the future. :disappointed:

**Comment by robbiebowman** [comment]
Don't sweat it. Just a minor annoyance. Opened up a small PR enhancement today anyway.

I'm also considering a new feature which uses the `tabs.mutedInfo.reason` (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/MutedInfo)

My idea is to add tabs to the `taggedManually` list if it appears in `regexList` and `mutedInfo.reason == "user"`. This would have the effect of making the browser mute toggle mimic the behaviour of the extension button (I think...). A usability feature I suppose.

**Comment by igorlogius** [comment]
>  making the browser mute mimic the behaviour of the extension button

I am not sure if this is a good idea, but i'll take a look at the PR.

**Pull request closed without merging**
